#!/usr/bin/env python3
"""Regenerate the repo listings on the homepage and the Projects page.

- docs/index.md: the 6 featured cards, from whichever repos are currently
  pinned on https://github.com/casact (via the GraphQL API; falls back to
  scraping the org profile page if no GITHUB_TOKEN is available).
- docs/projects.md: the full "Repositories" table, from all public repos
  in the org (REST API).

Both are regenerated between ``<!-- REPOS:START -->`` / ``<!-- REPOS:END -->``
markers. Run as part of .github/workflows/deploy-docs.yml (on push, daily
at 05:00 UTC, and on manual dispatch).
"""

from __future__ import annotations

import csv
import html
import sys
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from github_api import (  # noqa: E402
    DEFAULT_LANGUAGE_COLOR,
    LANGUAGE_COLORS,
    fetch_first_commit_date,
    fetch_org_repos,
    fetch_pinned_repos,
    repo_icon,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
INDEX_MD = REPO_ROOT / "docs" / "index.md"
PROJECTS_MD = REPO_ROOT / "docs" / "projects.md"
AREAS_CSV = REPO_ROOT / "docs" / "_data" / "repo_areas.csv"

START_MARKER = "<!-- REPOS:START -->"
END_MARKER = "<!-- REPOS:END -->"


def replace_between_markers(path: Path, generated: str) -> None:
    text = path.read_text()
    start = text.index(START_MARKER) + len(START_MARKER)
    end = text.index(END_MARKER)
    new_text = (
        text[:start]
        + "\n<!-- Generated by scripts/generate_repo_listings.py - do not edit by hand. -->\n\n"
        + generated
        + "\n\n"
        + text[end:]
    )
    path.write_text(new_text)


def read_areas() -> dict[str, str]:
    """Map repo name to area of practice, from the working group's own file.

    Nothing here comes from the GitHub API: which area a repo belongs to is a
    judgement about actuarial work, so it lives in a file people edit and
    review rather than in this script. A repo with no entry, or an empty one,
    simply shows no area until somebody who knows the project fills it in.
    """
    if not AREAS_CSV.exists():
        print(f"  {AREAS_CSV.name} not found; leaving the area column empty", file=sys.stderr)
        return {}
    with AREAS_CSV.open(newline="", encoding="utf-8") as fh:
        return {
            (row.get("repo") or "").strip(): (row.get("area") or "").strip()
            for row in csv.DictReader(fh)
        }


def report_area_gaps(repos: list[dict], areas: dict[str, str]) -> None:
    """Say what the mapping and the organization disagree about.

    A warning rather than an error: a repo renamed or added upstream must not
    be able to break the daily deploy, and an unclassified repo still belongs
    in the table.
    """
    names = {r["name"] for r in repos}
    unclassified = sorted(n for n in names if not areas.get(n))
    unknown = sorted(set(areas) - names)
    if unclassified:
        print(
            f"  {len(unclassified)} repo(s) with no area: {', '.join(unclassified)}",
            file=sys.stderr,
        )
    if unknown:
        print(
            f"  {AREAS_CSV.name} names {len(unknown)} repo(s) not in the org "
            f"(renamed or removed?): {', '.join(unknown)}",
            file=sys.stderr,
        )


def lang_dot(language: str | None) -> str:
    if not language:
        return ""
    color = LANGUAGE_COLORS.get(language, DEFAULT_LANGUAGE_COLOR)
    return (
        f'<span class="cas-repo-lang"><span class="cas-lang-dot" '
        f'style="background-color:{color}"></span>{html.escape(language)}</span>'
    )


def build_homepage_cards(repos: list[dict]) -> str:
    cards = []
    for r in repos:
        name = html.escape(r["name"])
        desc = html.escape(r["description"]) if r.get("description") else ""
        cards.append(
            f':::{{grid-item-card}} {repo_icon(16)} {name}\n'
            f":class-header: bg-light\n"
            f':link: {r["html_url"]}\n'
            f"{desc}\n\n"
            "+++\n"
            '```{raw} html\n'
            '<div class="cas-repo-meta">\n'
            f"  {lang_dot(r.get('language'))}\n"
            f'  <span class="cas-repo-stat"><i class="fa-solid fa-star"></i> {r["stargazers_count"]}</span>\n'
            f'  <span class="cas-repo-stat"><i class="fa-solid fa-code-fork"></i> {r["forks_count"]}</span>\n'
            "</div>\n"
            "```\n"
            ":::"
        )
    return '::::{grid} 1 1 3 3\n:gutter: 3\n\n' + "\n\n".join(cards) + "\n\n::::"


def format_started(d: date | None) -> str:
    """Format a first-commit date as ``YYYY MMM`` (e.g. ``2017 Jun``)."""
    if d is None:
        return ""
    return d.strftime("%Y %b")


def build_repo_row(r: dict) -> str:
    name = html.escape(r["name"])
    desc = html.escape(r["description"]) if r.get("description") else ""
    area = html.escape(r.get("area") or "")
    started = format_started(r.get("started"))
    return (
        "<tr>\n"
        f'  <td class="cas-repo-name"><a href="{r["html_url"]}" target="_blank" '
        f'rel="noopener">{repo_icon(14)}{name}</a></td>\n'
        f'  <td class="cas-repo-area">{area}</td>\n'
        f"  <td>{desc}</td>\n"
        f"  <td>{lang_dot(r.get('language'))}</td>\n"
        f'  <td><span class="cas-repo-stat"><i class="fa-solid fa-star"></i> {r["stargazers_count"]}</span></td>\n'
        f'  <td><span class="cas-repo-stat"><i class="fa-solid fa-code-fork"></i> {r["forks_count"]}</span></td>\n'
        f"  <td>{started}</td>\n"
        "</tr>"
    )


def build_projects_table(repos: list[dict]) -> str:
    repos_sorted = sorted(
        repos, key=lambda r: (-r["stargazers_count"], r["name"].lower())
    )
    rows = "\n".join(build_repo_row(r) for r in repos_sorted)
    intro = (
        f"All {len(repos)} public repositories in the "
        "[casact GitHub organization](https://github.com/casact), fetched "
        "directly from the GitHub API, except the areas of practice, which "
        "come from [a data file the working group maintains by "
        "hand](https://github.com/casact/casact.github.io/blob/main/docs/_data/repo_areas.csv)."
    )
    table = (
        '```{raw} html\n'
        '<div class="cas-repo-table-wrap">\n'
        '<table class="cas-repo-table">\n'
        "<thead>\n<tr>\n"
        "  <th>Repository</th>\n  <th>Area</th>\n  <th>Description</th>\n"
        "  <th>Language</th>\n"
        "  <th>Stars</th>\n  <th>Forks</th>\n  <th>Project Launched</th>\n"
        "</tr>\n</thead>\n<tbody>\n"
        + rows
        + "\n</tbody>\n</table>\n</div>\n```"
    )
    return intro + "\n\n" + table


def attach_started_dates(repos: list[dict]) -> None:
    """Set each repo's ``started`` field from its oldest commit date."""
    for i, r in enumerate(repos, start=1):
        name = r["name"]
        r["started"] = fetch_first_commit_date(name)


def main() -> None:
    print("Fetching pinned repos for the homepage...", file=sys.stderr)
    pinned = fetch_pinned_repos()
    print(f"  {len(pinned)} pinned repos", file=sys.stderr)
    replace_between_markers(INDEX_MD, build_homepage_cards(pinned))

    print("Fetching all org repos for the Projects page...", file=sys.stderr)
    all_repos = fetch_org_repos()
    print(f"  {len(all_repos)} repos", file=sys.stderr)
    areas = read_areas()
    report_area_gaps(all_repos, areas)
    for r in all_repos:
        r["area"] = areas.get(r["name"], "")
    print("Fetching first-commit dates...", file=sys.stderr)
    attach_started_dates(all_repos)
    replace_between_markers(PROJECTS_MD, build_projects_table(all_repos))

    print(
        f"Updated {INDEX_MD.name} ({len(pinned)} pinned) and "
        f"{PROJECTS_MD.name} ({len(all_repos)} repos).",
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
